# Generated by Django 4.0 on 2024-02-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('inStock', models.IntegerField()),
                ('availableStock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
